/*
 * Copyright (C) 2026 Giang Nguyen
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "inspectable.idl";
import "asyncinfo.idl";
import "eventtoken.idl";
import "windowscontracts.idl";
import "windows.foundation.idl";
import "windows.system.idl";

/* WebAccount and WebAccountProvider live in Windows.Security.Credentials, but
 * are declared here because windows.security.credentials.idl does not cover
 * the web account part of that namespace yet. */
namespace Windows.Security.Credentials {
    typedef enum WebAccountState WebAccountState;

    interface IWebAccount;
    interface IWebAccountProvider;

    runtimeclass WebAccount;
    runtimeclass WebAccountProvider;

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum WebAccountState
    {
        None      = 0,
        Connected = 1,
        Error     = 2,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.WebAccount),
        uuid(69473eb2-8031-49be-80bb-96cb46d99aba)
    ]
    interface IWebAccount : IInspectable
    {
        [propget] HRESULT WebAccountProvider([out, retval] Windows.Security.Credentials.WebAccountProvider **value);
        [propget] HRESULT UserName([out, retval] HSTRING *value);
        [propget] HRESULT State([out, retval] Windows.Security.Credentials.WebAccountState *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.WebAccountProvider),
        uuid(29dcc8c3-7ab9-4a7c-a336-b942f9dbf7c7)
    ]
    interface IWebAccountProvider : IInspectable
    {
        [propget] HRESULT Id([out, retval] HSTRING *value);
        [propget] HRESULT DisplayName([out, retval] HSTRING *value);
        [propget] HRESULT IconUri([out, retval] Windows.Foundation.Uri **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass WebAccount
    {
        [default] interface Windows.Security.Credentials.IWebAccount;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass WebAccountProvider
    {
        [default] interface Windows.Security.Credentials.IWebAccountProvider;
    }
}

namespace Windows.Security.Authentication.Web.Core {
    typedef enum FindAllWebAccountsStatus FindAllWebAccountsStatus;
    typedef enum WebTokenRequestPromptType WebTokenRequestPromptType;
    typedef enum WebTokenRequestStatus WebTokenRequestStatus;

    interface IFindAllAccountsResult;
    interface IWebAuthenticationCoreManagerStatics;
    interface IWebAuthenticationCoreManagerStatics2;
    interface IWebAuthenticationCoreManagerStatics4;
    interface IWebProviderError;
    interface IWebTokenRequest;
    interface IWebTokenRequestResult;
    interface IWebTokenResponse;

    runtimeclass FindAllAccountsResult;
    runtimeclass WebAuthenticationCoreManager;
    runtimeclass WebProviderError;
    runtimeclass WebTokenRequest;
    runtimeclass WebTokenRequestResult;
    runtimeclass WebTokenResponse;

    declare {
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Authentication.Web.Core.FindAllAccountsResult *>;
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Authentication.Web.Core.WebTokenRequestResult *>;
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.WebAccount *>;
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.WebAccountProvider *>;
        interface Windows.Foundation.Collections.IIterable<Windows.Security.Credentials.WebAccount *>;
        interface Windows.Foundation.Collections.IIterable<Windows.Security.Authentication.Web.Core.WebTokenResponse *>;
        interface Windows.Foundation.Collections.IIterator<Windows.Security.Credentials.WebAccount *>;
        interface Windows.Foundation.Collections.IIterator<Windows.Security.Authentication.Web.Core.WebTokenResponse *>;
        interface Windows.Foundation.Collections.IVectorView<Windows.Security.Credentials.WebAccount *>;
        interface Windows.Foundation.Collections.IVectorView<Windows.Security.Authentication.Web.Core.WebTokenResponse *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.FindAllAccountsResult *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.WebTokenRequestResult *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccount *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *>;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 5.0)
    ]
    enum FindAllWebAccountsStatus
    {
        Success                = 0,
        NotAllowedByProvider   = 1,
        NotSupportedByProvider = 2,
        ProviderError          = 3,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum WebTokenRequestPromptType
    {
        Default             = 0,
        ForceAuthentication = 1,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum WebTokenRequestStatus
    {
        Success                     = 0,
        UserCancel                  = 1,
        AccountSwitch               = 2,
        UserInteractionRequired     = 3,
        AccountProviderNotAvailable = 4,
        ProviderError               = 5,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 5.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.FindAllAccountsResult),
        uuid(a5812b5d-b72e-420c-86ab-aac0d7b7261f)
    ]
    interface IFindAllAccountsResult : IInspectable
    {
        [propget] HRESULT Accounts([out, retval] Windows.Foundation.Collections.IVectorView<Windows.Security.Credentials.WebAccount *> **value);
        [propget] HRESULT Status([out, retval] Windows.Security.Authentication.Web.Core.FindAllWebAccountsStatus *value);
        [propget] HRESULT ProviderError([out, retval] Windows.Security.Authentication.Web.Core.WebProviderError **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebProviderError),
        uuid(db191bb1-50c5-4809-8dca-09c99410245c)
    ]
    interface IWebProviderError : IInspectable
    {
        [propget] HRESULT ErrorCode([out, retval] UINT32 *value);
        [propget] HRESULT ErrorMessage([out, retval] HSTRING *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebTokenRequest),
        uuid(b77b4d68-adcb-4673-b364-0cf7b35caf97)
    ]
    interface IWebTokenRequest : IInspectable
    {
        [propget] HRESULT WebAccountProvider([out, retval] Windows.Security.Credentials.WebAccountProvider **value);
        [propget] HRESULT Scope([out, retval] HSTRING *value);
        [propget] HRESULT ClientId([out, retval] HSTRING *value);
        [propget] HRESULT PromptType([out, retval] Windows.Security.Authentication.Web.Core.WebTokenRequestPromptType *value);
        [propget] HRESULT Properties([out, retval] Windows.Foundation.Collections.IMap<HSTRING, HSTRING> **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebTokenRequestResult),
        uuid(c12a8305-d1f8-4483-8d54-38fe292784ff)
    ]
    interface IWebTokenRequestResult : IInspectable
    {
        [propget] HRESULT ResponseData([out, retval] Windows.Foundation.Collections.IVectorView<Windows.Security.Authentication.Web.Core.WebTokenResponse *> **value);
        [propget] HRESULT ResponseStatus([out, retval] Windows.Security.Authentication.Web.Core.WebTokenRequestStatus *value);
        [propget] HRESULT ResponseError([out, retval] Windows.Security.Authentication.Web.Core.WebProviderError **value);
        HRESULT InvalidateCacheAsync([out, retval] Windows.Foundation.IAsyncAction **operation);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebTokenResponse),
        uuid(67a7c5ca-83f6-44c6-a3b1-0eb69e41fa8a)
    ]
    interface IWebTokenResponse : IInspectable
    {
        [propget] HRESULT Token([out, retval] HSTRING *value);
        [propget] HRESULT ProviderError([out, retval] Windows.Security.Authentication.Web.Core.WebProviderError **value);
        [propget] HRESULT WebAccount([out, retval] Windows.Security.Credentials.WebAccount **value);
        [propget] HRESULT Properties([out, retval] Windows.Foundation.Collections.IMapView<HSTRING, HSTRING> **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManager),
        uuid(6aca7c92-a581-4479-9c10-752eff44fd34)
    ]
    interface IWebAuthenticationCoreManagerStatics : IInspectable
    {
        HRESULT GetTokenSilentlyAsync([in] Windows.Security.Authentication.Web.Core.WebTokenRequest *request,
                                      [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.WebTokenRequestResult *> **operation);
        HRESULT GetTokenSilentlyWithWebAccountAsync([in] Windows.Security.Authentication.Web.Core.WebTokenRequest *request,
                                                    [in] Windows.Security.Credentials.WebAccount *web_account,
                                                    [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.WebTokenRequestResult *> **operation);
        HRESULT RequestTokenAsync([in] Windows.Security.Authentication.Web.Core.WebTokenRequest *request,
                                  [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.WebTokenRequestResult *> **operation);
        HRESULT RequestTokenWithWebAccountAsync([in] Windows.Security.Authentication.Web.Core.WebTokenRequest *request,
                                                [in] Windows.Security.Credentials.WebAccount *web_account,
                                                [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.WebTokenRequestResult *> **operation);
        HRESULT FindAccountAsync([in] Windows.Security.Credentials.WebAccountProvider *provider, [in] HSTRING web_account_id,
                                 [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccount *> **operation);
        HRESULT FindAccountProviderAsync([in] HSTRING web_account_provider_id,
                                         [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *> **operation);
        HRESULT FindAccountProviderWithAuthorityAsync([in] HSTRING web_account_provider_id, [in] HSTRING authority,
                                                      [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *> **operation);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 3.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManager),
        uuid(f584184a-8b57-4820-b6a4-70a5b6fcf44a)
    ]
    interface IWebAuthenticationCoreManagerStatics2 : IInspectable
    {
        HRESULT FindAccountProviderWithAuthorityForUserAsync([in] HSTRING web_account_provider_id, [in] HSTRING authority,
                                                             [in] Windows.System.User *user,
                                                             [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *> **operation);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 5.0),
        exclusiveto(Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManager),
        uuid(54e633fe-96e0-41e8-9832-1298897c2aaf)
    ]
    interface IWebAuthenticationCoreManagerStatics4 : IInspectable
    {
        HRESULT FindAllAccountsAsync([in] Windows.Security.Credentials.WebAccountProvider *provider,
                                     [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.FindAllAccountsResult *> **operation);
        HRESULT FindAllAccountsWithClientIdAsync([in] Windows.Security.Credentials.WebAccountProvider *provider, [in] HSTRING client_id,
                                                 [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Authentication.Web.Core.FindAllAccountsResult *> **operation);
        HRESULT FindSystemAccountProviderAsync([in] HSTRING web_account_provider_id,
                                               [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *> **operation);
        HRESULT FindSystemAccountProviderWithAuthorityAsync([in] HSTRING web_account_provider_id, [in] HSTRING authority,
                                                            [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *> **operation);
        HRESULT FindSystemAccountProviderWithAuthorityForUserAsync([in] HSTRING web_account_provider_id, [in] HSTRING authority,
                                                                   [in] Windows.System.User *user,
                                                                   [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *> **operation);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 5.0),
        marshaling_behavior(agile)
    ]
    runtimeclass FindAllAccountsResult
    {
        [default] interface Windows.Security.Authentication.Web.Core.IFindAllAccountsResult;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass WebProviderError
    {
        [default] interface Windows.Security.Authentication.Web.Core.IWebProviderError;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass WebTokenRequest
    {
        [default] interface Windows.Security.Authentication.Web.Core.IWebTokenRequest;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass WebTokenRequestResult
    {
        [default] interface Windows.Security.Authentication.Web.Core.IWebTokenRequestResult;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass WebTokenResponse
    {
        [default] interface Windows.Security.Authentication.Web.Core.IWebTokenResponse;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        static(Windows.Security.Authentication.Web.Core.IWebAuthenticationCoreManagerStatics, Windows.Foundation.UniversalApiContract, 1.0),
        static(Windows.Security.Authentication.Web.Core.IWebAuthenticationCoreManagerStatics2, Windows.Foundation.UniversalApiContract, 3.0),
        static(Windows.Security.Authentication.Web.Core.IWebAuthenticationCoreManagerStatics4, Windows.Foundation.UniversalApiContract, 5.0),
        threading(both)
    ]
    runtimeclass WebAuthenticationCoreManager
    {
    }
}
